[profile.default]
auto_detect_solc = true
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
fuzz_runs = 10000
libs = ["dependencies"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
invariant = { runs = 256, depth = 15, fail_on_revert = true }

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
forge-gas-snapshot = "0.0.4"
forge-std = "1.9.2"
solmate = "6.7.0"
"@chainlink-contracts" = "1.2.0"

[soldeer]
recursive_deps = true
remappings_version = false
